# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taweewat Somboonpanyakul
email: taweewat@mit.edu
description: My personal webpage
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leogulus.github.io/" # the base hostname & protocol for your site
twitter_username: leogulus
github_username:  leogulus

# Build settings
markdown: kramdown
